# Configs for connecting to a database

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:
    url: jdbc:postgresql://ep-polished-sound-a177hhgs.ap-southeast-1.pg.koyeb.app/registration?user=Binus-admin&password=nVuIYpv02aOh
    username:
  jpa:
    ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true



    