# Configs for connecting to a database

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Maokettler92!#TA
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true